version: '3'
services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: vokabeln
    ports:
      - '${POSTGRES_PORT:-5434}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
